name: CICD

on:
  push:    
    branches: [master]
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./Frontend
      - run: npm install
      - run: npm run build
        env:
          CI: true
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSAccessKeyId }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSecretKey }}
          AWS_REGION: "ap-southeast-1" # optional: defaults to us-east-1
          SOURCE_DIR: "build" # optional: defaults to entire repository
